apiVersion: v2
name: example-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

sources:
- https://www.example.com

dependencies: # A list of the chart requirements (optional)
### ConfigMaps
- name: baseline
  version: "0.1.0"
  repository: https://hobops-helm-charts.storage.googleapis.com
  alias: example-config
### Secrets
- name: baseline
  version: "0.1.0"
  repository: https://hobops-helm-charts.storage.googleapis.com
  alias: example-secret
### Backends
- name: baseline
  version: "0.1.0"
  repository: https://hobops-helm-charts.storage.googleapis.com
  alias: example-backend
### Workers
- name: baseline
  version: "0.1.0"
  repository: https://hobops-helm-charts.storage.googleapis.com
  alias: example-worker
### Frontends
- name: baseline
  version: "0.1.0"
  repository: https://hobops-helm-charts.storage.googleapis.com
  alias: example-frontend
### Ingress
- name: baseline
  version: "0.1.0"
  repository: https://hobops-helm-charts.storage.googleapis.com
  alias: example-ingress

maintainers:
- name: DevOps