common-library:
  PersistentVolumeClaim:
    pvc-nfs:
      annotations:
        helm.sh/resource-policy: "keep"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: regional-pd-ssd
      volumeMode: Filesystem
  Deployment:
    nfs:
      replicas: 1
      strategy:
        type: Recreate
      selectorLabels:
        app: nfs
      image:
        repository: gcr.io/google_containers/volume-nfs
        tag: 0.8
      nodeSelector: {}
      command: ["bash","-c"]
      args:
      - /usr/local/bin/run_nfs.sh /exports /;
      service:
        ports:
        - name: nfs
          port: 2049
        - name: mountd
          port: 20048
        - name: rpcbind
          port: 111
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      volumeMounts:
      - mountPath: /exports
        name: vol-{{ .Release.Name }}
      volumes:
      - name: vol-{{ .Release.Name }}
        persistentVolumeClaim:
          claimName: pvc-{{ .Release.Name }}