common-library:
  DaemonSet:
    filebeat:
      annotations:
        reloader.stakater.com/auto: "true"
      selectorLabels:
        app: filebeat
      image:
        repository: docker.elastic.co/beats/filebeat
        tag: 7.10.1
      nodeSelector: {}
      args:
      - -c
      - /etc/filebeat.yml
      - -e
      envFrom:
      - configMapRef:
          name: filebeat-config-vars
      env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.nodeName
      securityContext:
        runAsUser: 0
      volumeMounts:
      - mountPath: /etc/filebeat.yml
        name: config
        readOnly: true
        subPath: filebeat.yml
      - mountPath: /usr/share/filebeat/data
        name: data
      - mountPath: /var/lib/docker/containers
        name: varlibdockercontainers
        readOnly: true
      - mountPath: /var/log
        name: varlog
        readOnly: true
      hostNetwork: false
      serviceAccountName: filebeat
      volumes:
      - configMap:
          defaultMode: 416
          name: filebeat-config-file
        name: config
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
        name: data
  ServiceAccount:
    filebeat: {}
  ConfigMap:
    filebeat-config-vars:
      data:
        LOGSTASH_HOST: elk
        LOGSTASH_PORT: "5044"
        FILEBEAT_SOURCE_NAME: changeme
    filebeat-config-file:
      data:
        filebeat.yml: |-
          filebeat.inputs:
          - type: container
            paths:
            - /var/log/containers/*.log
            processors:
            - add_labels:
                labels:
                  source: ${FILEBEAT_SOURCE_NAME}
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                - logs_path:
                    logs_path: "/var/log/containers/"      
          output.logstash:
            hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
  ClusterRole:
    filebeat:
      rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
          - pods
        verbs:
          - get
          - watch
          - list
  ClusterRoleBinding:
    filebeat:
      subjects:
      - kind: ServiceAccount
        name: filebeat
        namespace: '{{ .Release.Namespace }}'
