{{- if eq .Values.kind "ExternalSecret" }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "baseline.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval | default "30s" | quote }}
  secretStoreRef:
  {{- with .Values.secretStoreRef }}
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  target:
  {{- with .Values.target }}
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  dataFrom:
  {{- with .Values.dataFrom }}
  {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
