{{- if eq .Values.kind "Ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "baseline.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- /* ingressClassName */ -}}
  {{- if (hasKey .Values "ingressClassName") }}
  ingressClassName: {{ .Values.ingressClassName }}
  {{- end -}}

  {{- /* rules */ -}}
  {{- $env := .Values.paths -}}
  {{- if .Values.render_ingress_rules }}
  rules:
  {{- range .Values.hosts }}
  - host: {{ . }}
    http:
      paths:
        {{- tpl (toYaml $env) $ | nindent 6 }}
  {{- end }}
  {{- else }}
  {{- with .Values.rules }}
  rules:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end -}}
  {{- end -}}

  {{- /* tls */ -}}
  {{- if .Values.render_ingress_tls }}
  tls:
  - hosts:
    {{- range .Values.hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .Chart.Name }}-tls
  {{ else }}
  {{- with .Values.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end -}}
  {{- end -}}
{{- end }}
