{{- if eq .Values.kind "Secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baseline.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: {{ .Values.type | default "Opaque" }}
{{- with .Values.data }}
data:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with .Values.stringData }}
stringData:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
