{{- if or .Values.serviceAccount.create (eq .Values.kind "ServiceAccount") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "baseline.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
