{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "baseline.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "baseline.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "baseline.selectorLabels" . | nindent 6 }}
      {{- with .Values.selectorLabels }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "baseline.selectorLabels" . | nindent 8 }}
        {{- with .Values.selectorLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "baseline.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "baseline.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.command }}
        command: {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.args }}
        args: {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.envFrom }}
        envFrom: {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.env }}
        env: {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        ports:
        {{- range $host := .Values.service.ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort | default .port }}
          protocol: {{ .protocol }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
        volumeMounts: {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}