SecretsManagerSecret:
  test-app-aws-secretsmanager:
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    labels:
      app.kubernetes.io/part-of: test-app
    name: ack-secret-test-app-staging
    description: ack-secret-test-app-staging
    forceOverwriteReplicaSecret: false
    tags:
    - key: Site
      value: test-app
    - key: Configuration
      value: staging
    - key: Application
      value: Test App
    - key: k8s_namespace
      value: test-app
    - key: Managed-by
      value: kubernetes
