ClusterIssuer:
  letsencrypt:
    annotations:
      test: annotation
    email: changeme@example.com
    server: https://changeme-acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: changeme-clusterissuer-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: changeme-nginx