Issuer:
  # https://cert-manager.io/docs/configuration/acme/
  issuer-letsencrypt-staging:
    annotations:
      test: annotation
    acme:
      email: changeme@example.com
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: changeme-issuer-letsencrypt-staging-key
      solvers:
      - http01:
          ingress:
            class: nginx
  issuer-my-acme-server-with-eab:
    annotations:
      test: annotation
    acme:
      email: user@example.com
      server: https://my-acme-server-with-eab.com/directory
      externalAccountBinding:
        keyID: my-keyID-1
        keySecretRef:
          name: eab-secret
          key: secret
      privateKeySecretRef:
        name: example-issuer-account-key
      solvers:
      - http01:
          ingress:
            ingressClassName: nginx
      skipTLSVerify: false
      enableDurationFeature: false
      enableRevocationFeature: false
  # https://cert-manager.io/docs/configuration/acme/dns01/
  issuer-letsencrypt-prod-with-dns:
    annotations:
      test: annotation
    acme:
      email: changeme@example.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: changeme-issuer-letsencrypt-prod-key
      solvers:
      - dns01:
          cloudflare:
            email: user@example.com
            apiKeySecretRef:
              name: cloudflare-apikey-secret
              key: apikey
        selector:
          dnsZones:
          - 'example.com'
  # https://cert-manager.io/docs/configuration/ca/
  issuer-ca:
    annotations:
      test: annotation
    ca:
      secretName: example-ca-secret
      crlDistributionPoints:
      - "http://example.com"
  # https://cert-manager.io/docs/configuration/vault/
  issuer-vault-with-token:
    annotations:
      test: annotation
    vault:
      server: https://example-vault.com
      path: example/path
      caBundle: example-ca-bundle
      auth:
        tokenSecretRef:
          name: example-token-secret
          key: example-key
  issuer-vault-with-approle:
    annotations:
      test: annotation
    vault:
      server: https://example-vault.com
      path: example/path
      caBundle: example-ca-bundle
      auth:
        appRole:
          path: approle
          roleId: example-role-id
          secretRef:
            name: cert-manager-vault-approle
            key: secretId
  issuer-vault-with-kubernetes-service-account:
    annotations:
      test: annotation
    vault:
      path: pki_int/sign/example-dot-com
      server: https://vault.local
      auth:
        kubernetes:
          role: my-app-1
          mountPath: /v1/auth/kubernetes
          serviceAccountRef:
            name: vault-issuer
  # https://cert-manager.io/docs/configuration/selfsigned/
  issuer-selfsigned:
    annotations:
      test: annotation
    selfSigned: {}
  # https://cert-manager.io/docs/configuration/venafi/
  issuer-venafi:
    annotations:
      test: annotation
    venafi:
      zone: example-zone
      cloud:
        apiTokenSecretRef:
          name: example-api-token-secret
          key: example-key
