ClusterSecretStore:
  aws-secretsmanager:
    provider:
      aws:
        service: SecretsManager
        region: us-east-1
  aws-parameterstore:
    provider:
      aws:
        service: ParameterStore
        region: us-east-1
  vault-secretstore:
    provider:
      vault:
        auth:
          kubernetes:
            mountPath: kubernetes
            role: external-secrets-operator
            serviceAccountRef:
              name: external-secrets-operator
              namespace: infra
        path: secrets
        server: http://vault.infra.svc.cluster.local:8200
        version: v2