PushSecret:
    example-push-secret:
        refreshInterval: 1m
        secretStoreRefs:
        - name: aws-parameterstore
          kind: SecretStore
        selector:
          secret:
            name: pokedex-credentials
        data:
        - match:
            secretKey: best-pokemon
            remoteRefs:
            - remoteKey: my-first-parameter