ExternalSecret:
  example-aws-parameterstore:
    refreshInterval: 1m
    secretStoreRef:
      kind: ClusterSecretStore
      name: aws-parameterstore
    dataFrom:
    - extract: { key: '/test/example' }