CronJob:
  test-cronjob1:
    labels:
        labels: test-cronjob1
    annotations:
        annotation: test-cronjob1
    selectorLabels:
        selectorLabels: test-cronjob1
    serviceAnnotations:
        serviceAnnotations: test-cronjob1
        serviceAccountName: test-cronjob1
    podSecurityContext:
        fsGroup: 2000
    securityContext:
        privileged: false
    updateStrategy:
        type: RollingUpdate
    initContainers: {}
    image:
        repository: nginx
        tag: latest
        pullPolicy: IfNotPresent
    imagePullSecrets:
    - name: changeme
    envFrom:
    - configMapRef:
          name: test-configmap
    - secretRef:
          name: test-secret
    env:
    - name: FUZZ
      value: BUZZ