DaemonSet:
  test-daemonset:
    labels:
      labels: test-daemonset
    annotations:
      annotation: test-daemonset
    podAnnotations:
      podAnnotations: test-daemonset
    selectorLabels:
      selectorLabels: test-daemonset
    serviceAnnotations:
      serviceAnnotations: test-daemonset
      serviceAccountName: test-daemonset
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      privileged: false
    updateStrategy:
      type: RollingUpdate
    initContainers: {}
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    imagePullSecrets:
    - name: changeme
    envFrom:
    - configMapRef:
        name: test-configmap
    - secretRef:
        name: test-secret
    env:
    - name: FUZZ
      value: BUZZ
    command:
    - bash
    - -c
    args:
    - nginx -g "daemon off;"
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 2
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 2
    service:
      ports:
      - name: nginx
        port: 80
        protocol: TCP
      - name: nginx1
        port: 801
        protocol: TCP
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 200Mi
        cpu: 200m
    volumeMounts:
    - name: config-file
      mountPath: /etc/service.conf
      subPath: service.conf
      readOnly: true
    volumes:
    - name: config-file
      configMap:
        name: test-file-configmap
    nodeSelector:
      node: changeme
    hostAliases:
    - hostnames:
      - example.com
      ip: 1.1.1.1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "topology.kubernetes.io/zone"
              operator: In
              values: ["us-central1-a", "us-central1-b"]
    tolerations:
    - key: reserved-pool
      operator: Equal
      value: "true"
      effect: NoSchedule

