NetworkPolicy:
  test-networkpolicy:
    annotations:
      annotation: test-networkpolicy
    podSelector:
      matchLabels:
        changeme-match-label: "true"
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: changeme-namespace
        podSelector:
          matchLabels:
            type: changeme-label

