ServiceAccount:
  test-serviceaccount-without-secrets:
    annotations:
      annotation: test-serviceaccount
    labels:
      label: test-serviceaccount
    automountServiceAccountToken: false
    imagePullSecrets:
    - name: myregistrykey
  test-serviceaccount-without-imagepullsecrets:
    annotations:
      annotation: test-serviceaccount
    labels:
      label: test-serviceaccount
    automountServiceAccountToken: false
    secrets:
    - name: test-serviceaccount-token-rv8dl
  test-serviceaccount-with-automount:
    annotations:
      annotation: test-serviceaccount
    labels:
      label: test-serviceaccount
    automountServiceAccountToken: true
    imagePullSecrets:
    - name: myregistrykey
    secrets:
    - name: test-serviceaccount-token-rv8dl
  test-serviceaccount-without-annotations:
    labels:
      label: test-serviceaccount
    automountServiceAccountToken: false
    imagePullSecrets:
    - name: myregistrykey
    secrets:
    - name: test-serviceaccount-token-rv8dl
  test-serviceaccount-without-labels:
    annotations:
      annotation: test-serviceaccount
    automountServiceAccountToken: false
    imagePullSecrets:
    - name: myregistrykey
    secrets:
    - name: test-serviceaccount-token-rv8dl
