Service:
  test-service1:
    labels:
      labels: test-service1
    annotations:
      annotation: test-service1
    selectorLabels:
      selectorLabels: test-service1
    type: ClusterIP
    externalTrafficPolicy: Cluster
    loadBalancerIP: 2.2.2.2
    loadBalancerSourceRanges:
    - 90.254.0.0/24
    sessionAffinity: None
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    ports:
    - name: nginx1-service1
      port: 99
      protocol: TCP
    - name: nginx2-service1
      port: 999
      protocol: TCP
  test-service2:
    labels:
      lb-pool: public
    annotations:
      lbipam.cilium.io/ips: "38.58.138.130,2806:419:2:1180::10"
    selectorLabels:
      selectorLabels: test-service2
    type: LoadBalancer
    ipFamilyPolicy: RequireDualStack
    ipFamilies:
    - IPv4
    - IPv6
    externalTrafficPolicy: Local
    loadBalancerClass: io.cilium/bgp-control-plane
    allocateLoadBalancerNodePorts: false
    loadBalancerSourceRanges:
    - 0.0.0.0/0
    - ::/0
    ports:
    - name: https
      port: 443
      protocol: TCP
