PodMonitor:
  example-app:
    annotations:
      hobops.io/example: "true"
    labels:
      team: frontend
    jobLabel: app
    selector:
      matchLabels:
        app: example-app
    namespaceSelector:
      matchNames:
      - default
    podMetricsEndpoints:
    - port: web
      interval: 30s
      path: /metrics
