{{- define "library.ACK.SecretsManagerSecret" }}
{{- $data := .Values.SecretsManagerSecret }}
{{- $entry := index $data .name }}
---
apiVersion: {{ $entry.apiVersion | default "secretsmanager.services.k8s.aws/v1alpha1" }}
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with $entry.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  name: {{ tpl $entry.name $ }}
  {{- with $entry.description }}
  description: {{ tpl . $ | quote }}
  {{- end }}
  {{- if hasKey $entry "forceOverwriteReplicaSecret" }}
  forceOverwriteReplicaSecret: {{ $entry.forceOverwriteReplicaSecret }}
  {{- end }}
  {{- with $entry.tags }}
  tags:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
