{{- define "library.ArgoCD.AppProjects" }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProjects
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index .Values.AppProjects .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index .Values.AppProjects .name).labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  description: {{ (index .Values.AppProjects .name).description | default "" }}
  {{- with (index .Values.AppProjects .name).clusterResourceBlacklist }}
  clusterResourceBlacklist:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index .Values.AppProjects .name).clusterResourceWhitelist }}
  clusterResourceWhitelist:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index .Values.AppProjects .name).namespaceResourceBlacklist }}
  namespaceResourceBlacklist:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index .Values.AppProjects .name).namespaceResourceWhitelist }}
  namespaceResourceWhitelist:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index .Values.AppProjects .name).roles }}
  roles:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index .Values.AppProjects .name).destinations }}
  destinations:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index .Values.AppProjects .name).sourceRepos }}
  sourceRepos:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
