{{- define "library.CertManager.ClusterIssuer" }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ (index .Values.ClusterIssuer .name).email }}
    server: {{ (index .Values.ClusterIssuer .name).server }}
    {{- with (index .Values.ClusterIssuer .name).privateKeySecretRef }}
    privateKeySecretRef:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
    {{- with (index .Values.ClusterIssuer .name).solvers }}
    solvers:
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
