{{- define "library.CertManager.ClusterIssuer" }}
{{- $data := .Values.ClusterIssuer }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  acme:
    email: {{ (index $data .name).email }}
    server: {{ (index $data .name).server }}
    {{- with (index $data .name).privateKeySecretRef }}
    privateKeySecretRef:
      {{- tpl (toYaml .) $ | nindent 6 }}
    {{- end }}
    {{- with (index $data .name).solvers }}
    solvers:
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}
