{{- define "library.CertManager.Issuer" }}
{{- $data := .Values.Issuer }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with (index $data .name).acme }}
  acme:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).ca }}
  ca:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).vault }}
  vault:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).selfSigned }}
  selfSigned: {{ . }}
  {{- end }}
  {{- with (index $data .name).venafi }}
  venafi:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
