{{- define "library.ExternalSecretsOperator.PushSecret" }}
{{- $data := .Values.PushSecret }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ (index $data .name).refreshInterval | default "1m" }}
  {{- with (index $data .name).secretStoreRefs }}
  secretStoreRefs:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index $data .name).selector }}
  selector:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).data }}
  data:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
