{{- define "library.ExternalSecretsOperator.SecretStore" }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index .Values.SecretStore .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  controller: {{ (index .Values.SecretStore .name).controller | default ""}}
  {{- with (index .Values.SecretStore .name).provider }}
  provider:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index .Values.SecretStore .name).conditions }}
  conditions:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
