{{- define "library.ExternalSecretsOperator.ClusterExternalSecret" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index .Values.ClusterExternalSecret .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  externalSecretName: {{ (index .Values.ClusterExternalSecret .name).externalSecretName | default .name }}
  {{- with (index .Values.ClusterExternalSecret .name).namespaceSelector }}
  namespaceSelector:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  refreshTime: {{ (index .Values.ClusterExternalSecret .name).refreshTime | default "1m" }}
  {{- with (index .Values.ClusterExternalSecret .name).externalSecretSpec }}
  externalSecretSpec:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
