{{- define "library.ExternalSecretsOperator.ClusterSecretStore" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index .Values.ClusterSecretStore .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  controller: {{ (index .Values.ClusterSecretStore .name).controller | default ""}}
  {{- with (index .Values.ClusterSecretStore .name).provider }}
  provider:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index .Values.ClusterSecretStore .name).conditions }}
  conditions:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
