{{- define "library.ExternalSecretsOperator.ExternalSecret" }}
{{- $data := .Values.ExternalSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ (index $data .name).refreshInterval | default "1m"}}
  {{- with (index $data .name).secretStoreRef }}
  secretStoreRef:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).target }}
  target:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).data }}
  data:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).dataFrom }}
  dataFrom:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
