{{- define "library.ExternalSecretsOperator.SecretStore" }}
{{- $data := .Values.SecretStore }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  controller: {{ (index $data .name).controller | default ""}}
  {{- with (index $data .name).provider }}
  provider:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).conditions }}
  conditions:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
