{{- define "library.Istio.VirtualService" }}
{{- $data := .Values.VirtualService }}
{{- $entry := index $data .name }}
---
apiVersion: {{ $entry.apiVersion | default "networking.istio.io/v1" }}
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with $entry.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with $entry.gateways }}
  gateways:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.hosts }}
  hosts:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.exportTo }}
  exportTo:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.http }}
  http:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.tcp }}
  tcp:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
