{{- define "library.Kubernetes.NetworkPolicy" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with (index .Values.NetworkPolicy .name).podSelector }}
  podSelector:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index .Values.NetworkPolicy .name).policyTypes }}
  policyTypes:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index .Values.NetworkPolicy .name).ingress }}
  ingress:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
