{{- define "library.Kubernetes.ConfigMap" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
{{- with (index .Values.ConfigMap .name).data }}
data:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
