{{- define "library.Kubernetes.Secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index .Values.Secret .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index .Values.Secret .name).labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: {{ (index .Values.Secret .name).type | default "Opaque" }}
{{- with (index .Values.Secret .name).data }}
data:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with (index .Values.Secret .name).stringData }}
stringData:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
