{{- define "library.Kubernetes.StatefulSet" }}
{{- $data := .Values.StatefulSet }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- if (index $data .name).replicas }}
  replicas: {{ (index $data .name).replicas }}
  {{- end }}
  serviceName: {{ .name }}
  {{- with (index $data .name).updateStrategy }}
  updateStrategy:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).selectorLabels }}
  selector:
    matchLabels:
      {{- tpl (toYaml .) $ | nindent 6 }}
  {{- end }}
  template:
    metadata:
      {{- with (index $data .name).podAnnotations }}
      annotations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with (index $data .name).selectorLabels }}
      labels:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    spec:
      {{- with (index $data .name).imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ (index $data .name).serviceAccountName | default "default" }}
      {{- with (index $data .name).podSecurityContext }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with (index $data .name).initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .name }}
        {{- with (index $data .name).securityContext }}
        securityContext:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        image: "{{ (index $data .name).image.repository }}:{{ (index $data .name).image.tag }}"
        imagePullPolicy: {{ (index $data .name).image.pullPolicy }}
        {{- with (index $data .name).command }}
        command:
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with (index $data .name).args }}
        args:
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with (index $data .name).envFrom }}
        envFrom:
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with (index $data .name).env }}
        env:
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- if (index $data .name).service }}{{- if (index $data .name).service.ports }}
        ports:
        {{- range (index $data .name).service.ports }}
        - name: {{ .name }}
          containerPort: {{ .containerPort | default .port }}
          protocol: {{ .protocol }}
        {{- end }}
        {{- end }}{{- end }}
        {{- with (index $data .name).livenessProbe }}
        livenessProbe:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with (index $data .name).readinessProbe }}
        readinessProbe:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with (index $data .name).resources }}
        resources:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with (index $data .name).volumeMounts }}
        volumeMounts:
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with (index $data .name).volumes }}
      volumes:
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with (index $data .name).nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with (index $data .name).hostAliases }}
      hostAliases:
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with (index $data .name).affinity }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with (index $data .name).tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
  {{- with (index $data .name).volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- if (index $data .name).service }}{{- if (index $data .name).service.ports }}
---
  {{- $_ := set .Values "Workload" $data }}
  {{- $_ := set .Values "IsWorkload" true }}
  {{ include "library.Kubernetes.Service" (dict "name" .name "data" .data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{- end }}{{- end }}
{{- end }}