{{- define "library.Kubernetes.Role" }}
{{- $data := .Values.Role }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- with (index $data .name).rules }}
rules:
  {{- tpl (toYaml .) $ | nindent 0 }}
{{- end }}
{{- end }}
