{{- define "library.Kubernetes.Secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
type: {{ (index .Values.Secret .name).type | default "Opaque" }}
{{- with (index .Values.Secret .name).data }}
data:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- with (index .Values.Secret .name).stringData }}
stringData:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
