{{- define "library.Kubernetes.NetworkPolicy" }}
{{- $data := .Values.NetworkPolicy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with (index $data .name).podSelector }}
  podSelector:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).policyTypes }}
  policyTypes:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
  {{- with (index $data .name).ingress }}
  ingress:
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
