{{- define "library.Kubernetes.ServiceAccount" }}
{{- $data := .Values.ServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with (index $data .name).labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ (index $data .name).automountServiceAccountToken | default true }}
{{- with (index $data .name).imagePullSecrets }}
imagePullSecrets:
  {{- tpl (toYaml .) $ | nindent 0 }}
{{- end }}
{{- with (index $data .name).secrets }}
secrets:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
