{{- define "library.Kubernetes.StorageClass" }}
{{- $data := .Values.StorageClass }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  {{- with (index $data .name).annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
provisioner: {{ (index $data .name).provisioner }}
allowVolumeExpansion: {{ (index $data .name).allowVolumeExpansion | default "true" }}
reclaimPolicy: {{ (index $data .name).reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ (index $data .name).volumeBindingMode | default "Immediate" }}
{{- with (index $data .name).allowedTopologies }}
allowedTopologies:
  {{- tpl (toYaml .) $ | nindent 0 }}
{{- end }}
{{- with (index $data .name).parameters }}
parameters:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
