{{- define "library.Kubernetes.Namespace" }}
{{- $data := .Values.Namespace }}
{{- $entry := index $data .name }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  {{- with $entry.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $entry.labels }}
  labels:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
