{{ range $name, $data := .Values.SecretsManagerSecret }}
  {{ include "library.ACK.SecretsManagerSecret" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
