{{ range $name, $data := .Values.ClusterIssuer }}
  {{ include "library.CertManager.ClusterIssuer" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
