{{ range $name, $data := .Values.CiliumLoadBalancerIPPool }}
  {{ include "library.Cilium.CiliumLoadBalancerIPPool" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
