{{ range $name, $data := .Values.CiliumBGPNodeConfigOverride }}
  {{ include "library.Cilium.CiliumBGPNodeConfigOverride" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
