{{ range $name, $data := .Values.CiliumBGPPeerConfig }}
  {{ include "library.Cilium.CiliumBGPPeerConfig" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
