{{ range $name, $data := .Values.CiliumNetworkPolicy }}
  {{ include "library.Cilium.CiliumNetworkPolicy" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
