{{ range $name, $data := .Values.CiliumEgressGatewayPolicy }}
  {{ include "library.Cilium.CiliumEgressGatewayPolicy" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
