{{ range $name, $data := .Values.CiliumCIDRGroup }}
  {{ include "library.Cilium.CiliumCIDRGroup" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
