{{ range $name, $data := .Values.CiliumClusterwideNetworkPolicy }}
  {{ include "library.Cilium.CiliumClusterwideNetworkPolicy" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
