{{ range $name, $data := .Values.ExternalSecret }}
  {{ include "library.ExternalSecretsOperator.ExternalSecret" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
