{{ range $name, $data := .Values.PushSecret }}
  {{ include "library.ExternalSecretsOperator.PushSecret" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
