{{ range $name, $data := .Values.PushSecret }}
  {{ include "library.PushSecretsOperator.PushSecret" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
