{{ range $name, $data := .Values.ClusterSecretStore }}
  {{ include "library.ExternalSecretsOperator.ClusterSecretStore" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
