{{ range $name, $data := .Values.SecretStore }}
  {{ include "library.ExternalSecretsOperator.SecretStore" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
