{{ range $name, $data := .Values.ClusterExternalSecret }}
  {{ include "library.ExternalSecretsOperator.ClusterExternalSecret" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
