{{ range $name, $data := .Values.VirtualService }}
  {{ include "library.Istio.VirtualService" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
