{{ range $name, $data := .Values.TriggerAuthentication }}
  {{ include "library.Keda.TriggerAuthentication" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
