{{ range $name, $data := .Values.StatefulSet }}
  {{ include "library.Kubernetes.StatefulSet" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
