{{ range $name, $data := .Values.BackendTLSPolicy }}
  {{ include "library.Kubernetes.BackendTLSPolicy" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
