{{ range $name, $data := .Values.ClusterRole }}
  {{ include "library.Kubernetes.ClusterRole" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
