{{ range $name, $data := .Values.ServiceAccount }}
  {{ include "library.Kubernetes.ServiceAccount" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
