{{ range $name, $data := .Values.GatewayClass }}
  {{ include "library.Kubernetes.GatewayClass" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
