{{ range $name, $data := .Values.IPAddressPool }}
  {{ include "library.MetalLB.IPAddressPool" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
