{{ range $name, $data := .Values.L2Advertisement }}
  {{ include "library.MetalLB.L2Advertisement" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
