{{ range $name, $data := .Values.BGPAdvertisement }}
  {{ include "library.MetalLB.BGPAdvertisement" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
