{{ range $name, $data := .Values.ServiceMonitor }}
  {{ include "library.PrometheusOperator.ServiceMonitor" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
