{{ range $name, $data := .Values.AlertmanagerConfig }}
  {{ include "library.PrometheusOperator.AlertmanagerConfig" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
