{{ range $name, $data := .Values.PrometheusRule }}
  {{ include "library.PrometheusOperator.PrometheusRule" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
