{{ range $name, $data := .Values.PrometheusAgent }}
  {{ include "library.PrometheusOperator.PrometheusAgent" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
