{{ range $name, $data := .Values.Alertmanager }}
  {{ include "library.PrometheusOperator.Alertmanager" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
