{{ range $name, $data := .Values.Prometheus }}
  {{ include "library.PrometheusOperator.Prometheus" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
