{{ range $name, $data := .Values.PodMonitor }}
  {{ include "library.PrometheusOperator.PodMonitor" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
