{{ range $name, $data := .Values.ScrapeConfig }}
  {{ include "library.PrometheusOperator.ScrapeConfig" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
