{{ range $name, $data := .Values.TopicPermission }}
  {{ include "library.RabbitMQ.TopicPermission" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
