{{ range $name, $data := .Values.SchemaReplication }}
  {{ include "library.RabbitMQ.SchemaReplication" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
