{{ range $name, $data := .Values.OperatorPolicy }}
  {{ include "library.RabbitMQ.OperatorPolicy" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
