{{ range $name, $data := .Values.RabbitmqCluster }}
  {{ include "library.RabbitMQ.RabbitmqCluster" (dict "name" $name "data" $data "Release" $.Release "Values" $.Values "Template" $.Template ) }}
{{ end }}
