ClusterIssuer:
  letsencrypt:
    email: changeme@example.com
    server: https://changeme-acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: changeme-clusterissuer-letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: changeme-nginx
  letsencrypt-staging:
    email: changeme@example.com
    server: https://changeme-acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: changeme-clusterissuer-letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: changeme-nginx

ConfigMap:
  test-configmap:
    data:
      FOO: changeme

Secret:
  test-secret:
    data:
      FOO: changeme
    stringData:
      BAR: changeme

StorageClass:
  test-storageclass:
    provisioner: changeme
    allowVolumeExpansion: true
    reclaimPolicy: changeme
    volumeBindingMode: changeme
    parameters:
      type: changeme

NetworkPolicy:
  test-networkpolicy:
    podSelector:
      matchLabels:
        changeme-match-label: "true"
    policyTypes:
    - Ingress
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: changeme-namespace
        podSelector:
          matchLabels:
            type: changeme-label

