StatefulSet:
  test-statefulset1:
    labels:
      labels: test-statefulset1
    annotations:
      annotation: test-statefulset1
    podAnnotations:
      podAnnotations: test-statefulset1
    selectorLabels:
      selectorLabels: test-statefulset1
    serviceAnnotations:
      serviceAnnotations: test-statefulset1
#    serviceAccountName: test-statefulset1
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      externalTrafficPolicy: Cluster
      loadBalancerIP: 2.2.2.2
      loadBalancerSourceRanges:
      - 20.254.0.0/24
      sessionAffinity: None
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800
      ports:
      - name: nginx1-statefulset1
        port: 80
        protocol: TCP
      - name: nginx2-statefulset1
        port: 802
        protocol: TCP
  test-statefulset2:
    labels:
      labels: test-statefulset2
    annotations:
      annotation: test-statefulset2
    podAnnotations:
      podAnnotations: test-statefulset2
    selectorLabels:
      selectorLabels: test-statefulset2
    serviceAnnotations:
      serviceAnnotations: test-statefulset2
#    serviceAccountName: test-statefulset2
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      externalTrafficPolicy: Cluster
      loadBalancerIP: 2.2.2.2
      loadBalancerSourceRanges:
      - 20.254.0.0/24
      sessionAffinity: None
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800
      ports:
      - name: nginx1-statefulset2
        port: 80
        protocol: TCP
      - name: nginx2-statefulset2
        port: 802
        protocol: TCP

