ClusterIssuer: {}
CronJob: {}
Gateway: {}
GatewayClass: {}
HTTPRoute: {}
ConfigMap: {}
DaemonSet: {}
Deployment: {}
Job: {}
Secret: {}
StatefulSet: {}
StorageClass: {}
Namespace: {}
PodDisruptionBudget: {}
Postgres: {}
PostgresUser: {}
IAMRole: {}
IAMPolicy: {}
SecretsManagerSecret: {}
S3Bucket: {}
VirtualService: {}
ServiceMonitor: {}
PodMonitor: {}
Probe: {}
PrometheusRule: {}
Prometheus: {}
Alertmanager: {}
ThanosRuler: {}
PrometheusAgent: {}
ScrapeConfig: {}
AlertmanagerConfig: {}
RabbitmqCluster: {}
Vhost: {}
Exchange: {}
Queue: {}
Binding: {}
User: {}
Permission: {}
TopicPermission: {}
Policy: {}
OperatorPolicy: {}
Federation: {}
Shovel: {}
SchemaReplication: {}
SuperStream: {}
CiliumBGPClusterConfig: {}
CiliumBGPPeerConfig: {}
CiliumBGPAdvertisement: {}
CiliumLoadBalancerIPPool: {}
CiliumEgressGatewayPolicy: {}
CiliumNetworkPolicy: {}
CiliumClusterwideNetworkPolicy: {}
ReferenceGrant: {}
ValidatingAdmissionPolicy: {}
ValidatingAdmissionPolicyBinding: {}
ResourceQuota: {}
LimitRange: {}
IPAddressPool: {}
BGPPeer: {}
BGPAdvertisement: {}
BFDProfile: {}
L2Advertisement: {}
Community: {}
