{{- if eq .Values.kind "ConfigMap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baseline.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.data }}
data:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
