{{- if eq .Values.kind "ClusterSecretStore" }}
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: {{ include "baseline.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.provider }}
  provider:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}


