{{- if or .Values.service (eq .Values.kind "Service") }}{{- if .Values.service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseline.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | default "Cluster" }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  ports:
  {{- range $host := .Values.service.ports }}
  - name: {{ .name }}
    nodePort: {{ .nodePort }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    targetPort:  {{ .targetPort | default .port }}
  {{- end }}
  selector:
    {{- with .Values.selectorLabels }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
{{- end }}{{- end }}