# Kind fixture for ACK Secrets Manager Secret.
SecretsManagerSecret:
  ci-secretsmanagersecret:
    annotations:
      hobops.io/ci: "true"
    labels:
      app: ci-secretsmanagersecret
    name: common-library-ci-secret
    description: common-library-ci-secret
    forceOverwriteReplicaSecret: false
    tags:
    - key: Managed-by
      value: common-library-ci
