RabbitmqCluster:
  ci-topology-rmq:
    annotations:
      hobops.io/ci: "true"
    replicas: 1
    persistence:
      storage: "0"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi

OperatorPolicy:
  ci-operator-policy:
    annotations:
      hobops.io/ci: "true"
    name: ci-operator-policy
    vhost: vhost
    pattern: "^ci"
    applyTo: queues
    definition:
      expires: 60000
    rabbitmqClusterReference:
      name: ci-topology-rmq
