RabbitmqCluster:
  ci-topology-rmq:
    annotations:
      hobops.io/ci: "true"
    replicas: 1
    persistence:
      storage: "0"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi

Vhost:
  ci-vhost:
    annotations:
      hobops.io/ci: "true"
    name: vhost
    rabbitmqClusterReference:
      name: ci-topology-rmq

Exchange:
  ci-events-ex:
    annotations:
      hobops.io/ci: "true"
    name: ci_events_exchange
    vhost: vhost
    type: direct
    durable: true
    autoDelete: false
    rabbitmqClusterReference:
      name: ci-topology-rmq
