name: Helm Lint and Publish Charts

on:
#  push:
#    branches:
#      - main
#      - 'releases/**'
#  pull_request:
#    branches:
#      - main
#      - 'feat/**'
  workflow_dispatch:

jobs:
  deployment-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
