name: Helm Lint and Publish Charts

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'feat/**'
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Add hobops helm repo
        id: helm-add
        run: |
          helm repo add hobops https://hobops-helm-charts.storage.googleapis.com

      - name: Run chart-testing (lint)
        run: |
          ct lint --lint-conf scripts/lintconf.yaml --target-branch ${{ github.event.repository.default_branch }}

      - name: Run testing in common-library
        run: |
          cd charts/common-library
          make test_all

  publish:
    runs-on: ubuntu-latest
    needs: lint-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.2

      - name: Add hobops helm repo
        id: helm-add
        run: |
          helm repo add hobops https://hobops-helm-charts.storage.googleapis.com

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Publish helm charts
        id: helm-publish
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=/home/runner/work/helm-charts/helm-charts/credentials.json
          echo "[Credentials]" > ~/.boto
          echo "gs_service_key_file=${GOOGLE_APPLICATION_CREDENTIALS}" >> ~/.boto
          cat ~/.boto
          ./scripts/publish_helm_charts.sh
